- name: Get encrypted variables
  include_vars: snow_vars.yml

- name: Dump stored facts
  debug:
    msg: "my sys_id {{ snow_sys_id }}"


- name: Posting to SNOW API
  uri:
    url: https://{{ snow_instance_url }}/api/now/table/incident/{{ snow_sys_id }}
    user: "{{ snow_username }}"
    password: "{{ snow_password }}"
    method: PUT
    return_content: yes
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {"comments":"\n{{ snow_description }}"}
    status_code: 200
    validate_certs: no
  register: snow_response

- name: Dumping SNOW API Response
  debug:
    msg: "{{ snow_response.content }}"
