- name: "Get playbook variables"
  include_vars:
    dir: 'vars'
    extensions: ['yml']

- name: "Creating instance in Azure: Provisioning {{ instance_name }}"
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ instance_name }}"
    admin_username: "{{ my_admin_user }}"
    admin_password: "{{ my_admin_pass }}"
    storage_account_name: rhtest01
    os_type: "{{ oses[my_os].type }}"
    vm_size: "{{ my_vm_size  | default('Basic_A0') }}"
    image:
      offer: "{{ oses[my_os].offer }}"
      publisher: "{{ oses[my_os].publisher }}"
      sku: "{{ oses[my_os].sku }}"
      version: latest

#- name: Create an Azure VM extension to enable HTTPS WinRM listener
#  azure_rm_virtualmachine_extension:
#    name: winrm-extension
#    resource_group: "{{ azure_resource_group }}"
#    virtual_machine_name: "{{ inventory_hostname }}"
#    publisher: Microsoft.Compute
#    virtual_machine_extension_type: CustomScriptExtension
#    type_handler_version: 1.9
#    settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{winrm_enable_script}}"}'
#    auto_upgrade_minor_version: true

#- name: wait for the WinRM port to come online
#  wait_for:
#    port: 5986
#    host: '{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}'
#    timeout: 600
